name:                superevent
version:             0.1.0.0
github:              "agrafix/superevent"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2017 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            A simple opinionated event store implementation
category:            Database
description:         A simple opinionated event store implementation

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - uuid
    - text
    - hashable
    - unordered-containers
    - containers
    - mtl
    - aeson
    - transformers
    - stm
    - lifted-base
    - async
    - monad-control
    - transformers-base
    - vector
    - bytestring
    - time
    - conduit
    - hasql
    - hasql-pool
    - hasql-transaction
    - hasql-migration
    - timespan
    - random
    - contravariant
    - string-qq
  ghc-options: -Wall

tests:
  superevent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - superevent
