name:                superevent
version:             0.1.0.0
github:              "agrafix/superevent"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2017 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/agrafix/superevent#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - uuid
    - text
    - hashable
    - unordered-containers
    - containers
    - mtl
    - transformers
    - stm
    - lifted-base
    - async
    - monad-control
    - transformers-base
    - vector
    - bytestring
    - time
    - conduit
    - hasql
    - hasql-simple
  ghc-options: -Wall

executables:
  superevent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - superevent

tests:
  superevent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - superevent
