name:                superevent
version:             0.1.0.1
github:              "agrafix/superevent"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2018 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            A simple opinionated event store implementation
category:            Database
description:         A simple opinionated event store implementation

dependencies:
  - base >= 4.7 && < 5
  - vector
  - text
  - uuid
  - aeson
  - mtl
  - transformers
  - stm
  - async
  - conduit

library:
  source-dirs: src
  dependencies:
    - hashable
    - unordered-containers
    - containers
    - bytestring
    - time
    - hasql
    - hasql-pool
    - hasql-transaction
    - hasql-migration
    - timespan
    - random
    - contravariant
    - string-qq
  ghc-options: -Wall

tests:
  superevent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - superevent
      - hspec
      - temporary
      - QuickCheck
