on: [push]
name: build
jobs:
  runhaskell:
    name: superevent
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - run: stack test --fast
        env:
          PG_STRING: "host=localhost user=postgres password=postgres"
